### ISSUE TITLE
find_event_variants.py - removing intermediate files fails

### ISSUE THREAD

**Issue by JuliaPhilipp** [ajw2329/multiSpeciesAS#7]
Hi Andrew,
I think we talked about this before but I just wanted to write it down here:

find_event_variants.py runs perfectly with the --keep_intermediate flag but crashes without it. The problems are lines 307 and 308: neither the mpileup nor the sam file names contain the random id, that's why the rm fails. Therefore, commenting out lines 318 - 328 solves this issue. However, I am not sure which mpileup and sam files were supposed to be removed, that's why I didn't attempt to change the code.

PS: using the -fo flag in line 54 would make this script compatible with older bedtools versions as well

**Comment by ajw2329** [comment]
Fixed!
